// Content pack: "Spain Survival Spanish" — 80/20 curriculum for a Spain trip.
// Spanish variety: peninsular (Spain), including vosotros and Spain-specific vocabulary
// (patatas, zumo, billete, caña) where it differs from Latin America.
//
// Each lesson has: id, title, subtitle, icon, tips (grammar notes shown before drilling),
// and items: { es, de, ex_es?, ex_de?, note? }
// Card ids are derived from the Spanish text (see core/content.js), so editing this file
// does not scramble existing review progress.

export const LESSON_PACK_ID = "core-es";
export const LESSON_PACK_VERSION = 2;

export const LESSONS = [
  {
    id: "greetings",
    title: "Begrüßung & Höflichkeit",
    subtitle: "Hola, gracias, perdón",
    icon: "👋",
    tips: [
      "„¿Qué tal?“ ist in Spanien halb Frage, halb Gruß. Niemand erwartet einen echten Bericht – typische Antworten sind „Bien, ¿y tú?“, „Muy bien, gracias“ oder einfach „¿Qué tal?“ zurück.",
      "Zum Abschied sagt man in Spanien fast immer „Hasta luego“ – auch beim Verlassen eines Laden, selbst wenn man nie wiederkommt. „Adiós“ klingt endgültiger.",
      "Duzen ist in Spanien Standard (tú). „Usted“ brauchst du fast nur bei älteren Menschen, Ämtern oder sehr formellen Situationen."
    ],
    items: [
      { es: "Hola", de: "Hallo" },
      { es: "¡Buenas!", de: "Hallo! / Tag!", note: "kurze Allzweck-Begrüßung, sehr verbreitet" },
      { es: "Buenos días", de: "Guten Morgen", note: "bis zum Mittagessen, in Spanien also bis ca. 14 Uhr" },
      { es: "Buenas tardes", de: "Guten Tag / Guten Nachmittag", note: "ab dem Mittagessen bis zum Dunkelwerden" },
      { es: "Buenas noches", de: "Guten Abend / Gute Nacht", note: "Gruß und Abschied nach Einbruch der Dunkelheit" },
      { es: "¿Qué tal?", de: "Wie geht's?", note: "informell, oft auch einfach als Gruß", ex_es: "¡Hola! ¿Qué tal?", ex_de: "Hallo! Wie geht's?" },
      { es: "¿Cómo estás?", de: "Wie geht es dir?", note: "informell (tú)" },
      { es: "¿Cómo está?", de: "Wie geht es Ihnen?", note: "höflich (usted)" },
      { es: "Muy bien, gracias", de: "Sehr gut, danke" },
      { es: "Bien, ¿y tú?", de: "Gut, und dir?" },
      { es: "Regular", de: "Geht so / Mittelmäßig", note: "so sagt man es in Spanien, nicht „así así“" },
      { es: "Más o menos", de: "Mehr oder weniger / So lala" },
      { es: "Adiós", de: "Auf Wiedersehen", note: "klingt endgültig" },
      { es: "Hasta luego", de: "Bis später / Tschüss", note: "der Standard-Abschied in Spanien" },
      { es: "Hasta mañana", de: "Bis morgen" },
      { es: "Hasta pronto", de: "Bis bald" },
      { es: "Nos vemos", de: "Wir sehen uns" },
      { es: "Por favor", de: "Bitte" },
      { es: "Gracias", de: "Danke" },
      { es: "Muchas gracias", de: "Vielen Dank" },
      { es: "De nada", de: "Gern geschehen / Keine Ursache" },
      { es: "Perdón", de: "Entschuldigung / Verzeihung", note: "Allzweckwort, auch beim Anrempeln" },
      { es: "Perdona", de: "Entschuldige", note: "informell (tú)" },
      { es: "Perdone", de: "Entschuldigen Sie", note: "höflich (usted) – so macht man Personal aufmerksam" },
      { es: "Disculpe", de: "Entschuldigen Sie", note: "höflich (usted)" },
      { es: "Lo siento", de: "Es tut mir leid" },
      { es: "Sí", de: "Ja" },
      { es: "No", de: "Nein" },
      { es: "Vale", de: "Okay / In Ordnung", note: "das häufigste Wort in Spanien" },
      { es: "Encantado / Encantada", de: "Freut mich", note: "Mann sagt „encantado“, Frau „encantada“" },
      { es: "Igualmente", de: "Gleichfalls / Ebenso", note: "Antwort auf „Encantado“ oder „Buen provecho“" },
      { es: "Salud", de: "Gesundheit / Prost", note: "beim Niesen und beim Anstoßen" }
    ]
  },
  {
    id: "basics",
    title: "Bausteine & kleine Wörter",
    subtitle: "und, aber, sehr, hier, mit, ohne",
    icon: "🧱",
    tips: [
      "Jedes Nomen hat ein Geschlecht: „el“ (männlich) / „la“ (weiblich), im Plural „los“ / „las“. Faustregel: Endung -o meist männlich, -a meist weiblich.",
      "Verneint wird ganz einfach mit „no“ direkt vor dem Verb: „No entiendo.“ / „No hay.“ / „No me gusta.“",
      "„muy“ steht vor Adjektiven (muy bien, muy caro), „mucho“ vor Nomen oder nach Verben (mucho calor, gracias por todo)."
    ],
    items: [
      { es: "el / la", de: "der / die", note: "bestimmter Artikel, Singular", ex_es: "el coche, la casa", ex_de: "das Auto, das Haus" },
      { es: "los / las", de: "die", note: "bestimmter Artikel, Plural" },
      { es: "un / una", de: "ein / eine", ex_es: "un café, una cerveza", ex_de: "ein Kaffee, ein Bier" },
      { es: "y", de: "und", note: "wird zu „e“ vor i-/hi-Laut: padre e hijo" },
      { es: "o", de: "oder" },
      { es: "pero", de: "aber" },
      { es: "también", de: "auch", ex_es: "Yo también.", ex_de: "Ich auch." },
      { es: "tampoco", de: "auch nicht", ex_es: "Yo tampoco.", ex_de: "Ich auch nicht." },
      { es: "muy", de: "sehr", note: "vor Adjektiven", ex_es: "muy bien", ex_de: "sehr gut" },
      { es: "mucho", de: "viel", note: "vor Nomen / nach Verben", ex_es: "mucho calor", ex_de: "große Hitze" },
      { es: "un poco", de: "ein wenig / ein bisschen" },
      { es: "más", de: "mehr", ex_es: "un poco más", ex_de: "ein bisschen mehr" },
      { es: "menos", de: "weniger" },
      { es: "otro / otra", de: "ein anderer / noch ein", ex_es: "Otra caña, por favor.", ex_de: "Noch ein Bier, bitte." },
      { es: "todo", de: "alles" },
      { es: "nada", de: "nichts" },
      { es: "algo", de: "etwas" },
      { es: "aquí", de: "hier" },
      { es: "allí", de: "dort" },
      { es: "esto", de: "das (hier)", note: "wenn man auf etwas zeigt", ex_es: "¿Qué es esto?", ex_de: "Was ist das?" },
      { es: "este / esta", de: "dieser / diese" },
      { es: "con", de: "mit" },
      { es: "sin", de: "ohne" },
      { es: "para", de: "für / um zu", ex_es: "para mí", ex_de: "für mich" },
      { es: "de", de: "von / aus", ex_es: "Soy de Alemania.", ex_de: "Ich bin aus Deutschland." },
      { es: "en", de: "in / auf" },
      { es: "a", de: "zu / nach", ex_es: "Voy a la playa.", ex_de: "Ich gehe zum Strand." },
      { es: "bien / mal", de: "gut / schlecht", note: "Adverbien (wie etwas läuft)" },
      { es: "bueno / malo", de: "gut / schlecht", note: "Adjektive (wie etwas ist)" },
      { es: "grande / pequeño", de: "groß / klein" },
      { es: "ya", de: "schon / jetzt" },
      { es: "todavía no", de: "noch nicht" },
      { es: "siempre", de: "immer" },
      { es: "nunca", de: "nie" },
      { es: "porque", de: "weil", note: "ein Wort, ohne Akzent – im Gegensatz zu „¿por qué?“ (warum)" },
      { es: "si", de: "wenn / falls", note: "ohne Akzent! „sí“ mit Akzent heißt „ja“" },
      { es: "¿verdad?", de: "oder? / nicht wahr?", note: "Rückfrage am Satzende" }
    ]
  },
  {
    id: "questions",
    title: "Fragewörter",
    subtitle: "qué, dónde, cuánto, cómo",
    icon: "❓",
    tips: [
      "In Fragen tragen diese Wörter immer einen Akzent (qué, dónde, cuándo…). Ohne Akzent haben sie eine andere Funktion: „¿Por qué?“ = warum, „porque“ = weil; „¿Qué?“ = was, „que“ = dass.",
      "Fragen bekommen im Spanischen ein umgedrehtes Fragezeichen am Anfang: ¿…?",
      "„¿Qué?“ fragt allgemein („¿Qué quieres?“), „¿Cuál?“ fragt nach einer Auswahl („¿Cuál prefieres?“)."
    ],
    items: [
      { es: "¿Qué?", de: "Was?", ex_es: "¿Qué es esto?", ex_de: "Was ist das?" },
      { es: "¿Quién?", de: "Wer?", ex_es: "¿Quién es?", ex_de: "Wer ist das?" },
      { es: "¿Cómo?", de: "Wie?", ex_es: "¿Cómo te llamas?", ex_de: "Wie heißt du?" },
      { es: "¿Cuándo?", de: "Wann?", ex_es: "¿Cuándo abre?", ex_de: "Wann öffnet es?" },
      { es: "¿Dónde?", de: "Wo?", ex_es: "¿Dónde está la playa?", ex_de: "Wo ist der Strand?" },
      { es: "¿Adónde?", de: "Wohin?", ex_es: "¿Adónde vamos?", ex_de: "Wohin gehen wir?" },
      { es: "¿De dónde?", de: "Woher?", ex_es: "¿De dónde eres?", ex_de: "Woher kommst du?" },
      { es: "¿Por qué?", de: "Warum?", note: "zwei Wörter mit Akzent – Antwort beginnt mit „porque“" },
      { es: "¿Para qué?", de: "Wofür? / Wozu?" },
      { es: "¿Cuál?", de: "Welcher? / Welche?", note: "Auswahl aus mehreren", ex_es: "¿Cuál prefieres?", ex_de: "Welchen bevorzugst du?" },
      { es: "¿Cuáles?", de: "Welche?", note: "Plural von cuál" },
      { es: "¿Cuánto?", de: "Wie viel?", ex_es: "¿Cuánto cuesta?", ex_de: "Wie viel kostet es?" },
      { es: "¿Cuánto tiempo?", de: "Wie lange?" },
      { es: "¿Cuántos? / ¿Cuántas?", de: "Wie viele?", note: "passt sich dem Geschlecht an: ¿Cuántos días? / ¿Cuántas horas?" },
      { es: "¿A qué hora?", de: "Um wie viel Uhr?", ex_es: "¿A qué hora abre?", ex_de: "Um wie viel Uhr öffnet es?" }
    ]
  },
  {
    id: "numbers",
    title: "Zahlen & Mengen",
    subtitle: "Zählen, Preise, Portionen",
    icon: "🔢",
    tips: [
      "„uno“ wird vor einem Nomen zu „un“ (un café) bzw. „una“ (una cerveza). Genauso: veintiún euros.",
      "16 bis 29 schreibt man zusammen (dieciséis, veintitrés). Ab 31 mit „y“: treinta y uno, cuarenta y cinco.",
      "„cien“ heißt genau 100. Kommt noch etwas dazu, wird es „ciento“: ciento veinte. Unregelmäßig sind 500 quinientos, 700 setecientos, 900 novecientos."
    ],
    items: [
      { es: "cero", de: "null" }, { es: "uno", de: "eins" }, { es: "dos", de: "zwei" },
      { es: "tres", de: "drei" }, { es: "cuatro", de: "vier" }, { es: "cinco", de: "fünf" },
      { es: "seis", de: "sechs" }, { es: "siete", de: "sieben" }, { es: "ocho", de: "acht" },
      { es: "nueve", de: "neun" }, { es: "diez", de: "zehn" }, { es: "once", de: "elf" },
      { es: "doce", de: "zwölf" }, { es: "trece", de: "dreizehn" }, { es: "catorce", de: "vierzehn" },
      { es: "quince", de: "fünfzehn" }, { es: "dieciséis", de: "sechzehn" }, { es: "diecisiete", de: "siebzehn" },
      { es: "dieciocho", de: "achtzehn" }, { es: "diecinueve", de: "neunzehn" }, { es: "veinte", de: "zwanzig" },
      { es: "veintiuno", de: "einundzwanzig", note: "vor Nomen: veintiún euros" },
      { es: "veintidós", de: "zweiundzwanzig" },
      { es: "treinta", de: "dreißig" },
      { es: "treinta y uno", de: "einunddreißig", note: "ab 31 immer mit „y“" },
      { es: "cuarenta", de: "vierzig" }, { es: "cincuenta", de: "fünfzig" }, { es: "sesenta", de: "sechzig" },
      { es: "setenta", de: "siebzig" }, { es: "ochenta", de: "achtzig" }, { es: "noventa", de: "neunzig" },
      { es: "cien", de: "hundert", note: "genau 100" },
      { es: "ciento veinte", de: "hundertzwanzig", note: "ab 101: ciento…" },
      { es: "doscientos", de: "zweihundert" },
      { es: "quinientos", de: "fünfhundert", note: "unregelmäßig" },
      { es: "mil", de: "tausend" },
      { es: "el euro / los euros", de: "der Euro / die Euros" },
      { es: "el céntimo", de: "der Cent" },
      { es: "medio / media", de: "halb", ex_es: "medio kilo", ex_de: "ein halbes Kilo" },
      { es: "unos / unas", de: "ein paar / einige", ex_es: "unas tapas", ex_de: "ein paar Tapas" },
      { es: "un par de", de: "ein Paar / zwei", note: "wörtlich ein Paar, meint meist genau zwei" },
      { es: "primero / primera", de: "erster / erste" },
      { es: "segundo / segunda", de: "zweiter / zweite" },
      { es: "tercero / tercera", de: "dritter / dritte" }
    ]
  },
  {
    id: "clock",
    title: "Uhrzeit & Tageszeiten",
    subtitle: "¿Qué hora es? A las ocho.",
    icon: "🕒",
    tips: [
      "Achtung, Falle für Deutsche: Spanisch zählt wie Englisch von der vollen Stunde weg. „Es la una y media“ = 1:30, also „halb zwei“ auf Deutsch. Nie wörtlich aus dem Deutschen übersetzen!",
      "Für 1 Uhr: „Es la una“ (Singular). Ab 2 Uhr: „Son las dos, son las tres…“ (Plural).",
      "y media = halb drüber, y cuarto = Viertel nach, menos cuarto = Viertel vor, en punto = Punkt/genau."
    ],
    items: [
      { es: "¿Qué hora es?", de: "Wie spät ist es?" },
      { es: "Es la una", de: "Es ist ein Uhr", note: "nur bei 1 Uhr: „es la“" },
      { es: "Son las dos", de: "Es ist zwei Uhr", note: "ab 2 Uhr: „son las“" },
      { es: "Es la una y media", de: "Es ist halb zwei", note: "1:30 – wörtlich „eins und halb“" },
      { es: "Son las tres y cuarto", de: "Es ist Viertel nach drei", note: "3:15" },
      { es: "Son las cuatro menos cuarto", de: "Es ist Viertel vor vier", note: "3:45" },
      { es: "Son las ocho y diez", de: "Es ist zehn nach acht", note: "8:10" },
      { es: "Son las cinco en punto", de: "Es ist genau fünf Uhr" },
      { es: "a las ocho", de: "um acht Uhr", ex_es: "Cenamos a las nueve.", ex_de: "Wir essen um neun zu Abend." },
      { es: "sobre las ocho", de: "gegen acht Uhr", note: "sehr praktisch für Verabredungen" },
      { es: "el mediodía", de: "der Mittag" },
      { es: "la medianoche", de: "die Mitternacht" },
      { es: "de la mañana", de: "morgens / vormittags" },
      { es: "de la tarde", de: "nachmittags / abends", note: "bis es dunkel wird" },
      { es: "de la noche", de: "nachts / abends" },
      { es: "la mañana", de: "der Morgen", note: "mit Artikel = Tageszeit; „mañana“ allein = morgen" },
      { es: "ahora", de: "jetzt" },
      { es: "luego / después", de: "später / danach" },
      { es: "pronto", de: "bald" },
      { es: "temprano", de: "früh" },
      { es: "tarde", de: "spät", note: "„la tarde“ mit Artikel = der Nachmittag" },
      { es: "el horario", de: "die Öffnungszeiten" },
      { es: "¿A qué hora cierra?", de: "Wann schließt es?" }
    ]
  },
  {
    id: "calendar",
    title: "Tage, Monate & Datum",
    subtitle: "lunes, enero, hoy, mañana",
    icon: "📅",
    tips: [
      "Wochentage und Monate schreibt man im Spanischen klein – anders als im Deutschen.",
      "„Am Montag“ heißt einfach „el lunes“ – ohne Präposition. „Los lunes“ heißt „montags“ (immer).",
      "Datum: „el 15 de septiembre“ – Zahl, „de“, Monat."
    ],
    items: [
      { es: "hoy", de: "heute" },
      { es: "mañana", de: "morgen", note: "ohne Artikel = morgen (der Tag danach)" },
      { es: "pasado mañana", de: "übermorgen" },
      { es: "ayer", de: "gestern" },
      { es: "el día", de: "der Tag" },
      { es: "la semana", de: "die Woche" },
      { es: "el fin de semana", de: "das Wochenende" },
      { es: "la semana que viene", de: "nächste Woche" },
      { es: "el mes", de: "der Monat" },
      { es: "el año", de: "das Jahr" },
      { es: "lunes", de: "Montag", note: "klein geschrieben", ex_es: "el lunes", ex_de: "am Montag" },
      { es: "martes", de: "Dienstag" }, { es: "miércoles", de: "Mittwoch" },
      { es: "jueves", de: "Donnerstag" }, { es: "viernes", de: "Freitag" },
      { es: "sábado", de: "Samstag" }, { es: "domingo", de: "Sonntag" },
      { es: "enero", de: "Januar" }, { es: "febrero", de: "Februar" }, { es: "marzo", de: "März" },
      { es: "abril", de: "April" }, { es: "mayo", de: "Mai" }, { es: "junio", de: "Juni" },
      { es: "julio", de: "Juli" }, { es: "agosto", de: "August" }, { es: "septiembre", de: "September" },
      { es: "octubre", de: "Oktober" }, { es: "noviembre", de: "November" }, { es: "diciembre", de: "Dezember" },
      { es: "¿Qué día es hoy?", de: "Welcher Tag ist heute?" },
      { es: "el 15 de septiembre", de: "der 15. September" },
      { es: "un día festivo", de: "ein Feiertag", note: "dann ist in Spanien oft alles zu" }
    ]
  },
  {
    id: "verbs-core",
    title: "Die vier Grundverben",
    subtitle: "ser, estar, tener, hay",
    icon: "🧩",
    tips: [
      "SER = was etwas dauerhaft ist (Herkunft, Beruf, Charakter, Eigenschaft). ESTAR = Zustand und Ort (wo etwas ist, wie es einem gerade geht).",
      "Merksatz: „Soy alemán“ (dauerhaft) – „Estoy cansado“ (gerade jetzt). Beides heißt „ich bin“.",
      "TENER = haben. Spanisch benutzt es auch dort, wo Deutsch „sein“ sagt: tengo hambre (ich habe Hunger), tengo sed (Durst), tengo 40 años (ich bin 40).",
      "HAY (von haber) heißt „es gibt“ und bleibt immer gleich – egal ob Einzahl oder Mehrzahl: hay un baño / hay dos baños."
    ],
    items: [
      { es: "yo soy", de: "ich bin", note: "ser – Identität", ex_es: "Soy alemán.", ex_de: "Ich bin Deutscher." },
      { es: "tú eres", de: "du bist", note: "ser" },
      { es: "él / ella / usted es", de: "er/sie ist, Sie sind", note: "ser" },
      { es: "nosotros somos", de: "wir sind", note: "ser" },
      { es: "vosotros sois", de: "ihr seid", note: "ser – nur in Spanien" },
      { es: "ellos / ellas / ustedes son", de: "sie sind, Sie sind", note: "ser" },
      { es: "yo estoy", de: "ich bin", note: "estar – Zustand/Ort", ex_es: "Estoy cansado.", ex_de: "Ich bin müde." },
      { es: "tú estás", de: "du bist", note: "estar" },
      { es: "él / ella / usted está", de: "er/sie ist, Sie sind", note: "estar", ex_es: "¿Dónde está el hotel?", ex_de: "Wo ist das Hotel?" },
      { es: "nosotros estamos", de: "wir sind", note: "estar", ex_es: "Estamos de vacaciones.", ex_de: "Wir sind im Urlaub." },
      { es: "vosotros estáis", de: "ihr seid", note: "estar" },
      { es: "ellos / ellas / ustedes están", de: "sie sind, Sie sind", note: "estar" },
      { es: "yo tengo", de: "ich habe", note: "tener", ex_es: "Tengo hambre.", ex_de: "Ich habe Hunger." },
      { es: "tú tienes", de: "du hast", note: "tener" },
      { es: "él / ella / usted tiene", de: "er/sie hat, Sie haben", note: "tener" },
      { es: "nosotros tenemos", de: "wir haben", note: "tener" },
      { es: "vosotros tenéis", de: "ihr habt", note: "tener" },
      { es: "ellos / ellas / ustedes tienen", de: "sie haben, Sie haben", note: "tener" },
      { es: "tengo que...", de: "ich muss...", note: "tener que + Infinitiv", ex_es: "Tengo que irme.", ex_de: "Ich muss los." },
      { es: "hay que...", de: "man muss...", note: "unpersönlich", ex_es: "Hay que reservar.", ex_de: "Man muss reservieren." },
      { es: "hay", de: "es gibt", note: "immer unveränderlich", ex_es: "Hay dos baños.", ex_de: "Es gibt zwei Toiletten." },
      { es: "no hay", de: "es gibt nicht / es gibt keine", ex_es: "No hay mesas libres.", ex_de: "Es gibt keine freien Tische." },
      { es: "Tengo sed", de: "Ich habe Durst" },
      { es: "Tengo frío / calor", de: "Mir ist kalt / warm", note: "wörtlich: ich habe Kälte/Hitze" }
    ]
  },
  {
    id: "verbs-regular",
    title: "Regelmäßige Verben",
    subtitle: "Das Endungs-System: -ar, -er, -ir",
    icon: "🔧",
    tips: [
      "Es gibt genau drei Verbgruppen: -ar, -er, -ir. Endung abschneiden, Personalendung anhängen – damit beherrschst du hunderte Verben auf einmal.",
      "-ar: -o, -as, -a, -amos, -áis, -an  |  -er: -o, -es, -e, -emos, -éis, -en  |  -ir: -o, -es, -e, -imos, -ís, -en",
      "-er und -ir unterscheiden sich nur bei „wir“ und „ihr“ (comemos/coméis vs. vivimos/vivís). Alles andere ist identisch.",
      "Das Personalpronomen (yo, tú…) lässt man meist weg – die Endung sagt schon, wer gemeint ist."
    ],
    items: [
      { es: "hablar", de: "sprechen", note: "Modell für -ar" },
      { es: "hablo", de: "ich spreche", note: "-ar", ex_es: "Hablo un poco de español.", ex_de: "Ich spreche ein bisschen Spanisch." },
      { es: "hablas", de: "du sprichst", note: "-ar" },
      { es: "habla", de: "er/sie spricht, Sie sprechen", note: "-ar" },
      { es: "hablamos", de: "wir sprechen", note: "-ar" },
      { es: "habláis", de: "ihr sprecht", note: "-ar" },
      { es: "hablan", de: "sie/Sie sprechen", note: "-ar" },
      { es: "comer", de: "essen", note: "Modell für -er" },
      { es: "como", de: "ich esse", note: "-er" },
      { es: "comes", de: "du isst", note: "-er" },
      { es: "come", de: "er/sie isst, Sie essen", note: "-er" },
      { es: "comemos", de: "wir essen", note: "-er", ex_es: "¿Dónde comemos hoy?", ex_de: "Wo essen wir heute?" },
      { es: "coméis", de: "ihr isst", note: "-er" },
      { es: "comen", de: "sie/Sie essen", note: "-er" },
      { es: "vivir", de: "leben / wohnen", note: "Modell für -ir" },
      { es: "vivo", de: "ich lebe / wohne", note: "-ir", ex_es: "Vivo en Alemania.", ex_de: "Ich wohne in Deutschland." },
      { es: "vives", de: "du lebst / wohnst", note: "-ir" },
      { es: "vive", de: "er/sie lebt, Sie leben", note: "-ir" },
      { es: "vivimos", de: "wir leben / wohnen", note: "-ir" },
      { es: "vivís", de: "ihr lebt / wohnt", note: "-ir" },
      { es: "viven", de: "sie/Sie leben", note: "-ir" },
      { es: "tomar", de: "nehmen / trinken", note: "regelmäßig -ar; im Lokal: etwas zu sich nehmen", ex_es: "¿Qué vas a tomar?", ex_de: "Was möchtest du trinken/nehmen?" },
      { es: "beber", de: "trinken", note: "regelmäßig -er" },
      { es: "pagar", de: "bezahlen", note: "regelmäßig -ar" },
      { es: "comprar", de: "kaufen", note: "regelmäßig -ar" },
      { es: "buscar", de: "suchen", note: "regelmäßig -ar", ex_es: "Busco la estación.", ex_de: "Ich suche den Bahnhof." },
      { es: "esperar", de: "warten / hoffen", note: "regelmäßig -ar" },
      { es: "trabajar", de: "arbeiten", note: "regelmäßig -ar" },
      { es: "aprender", de: "lernen", note: "regelmäßig -er" },
      { es: "abrir", de: "öffnen", note: "regelmäßig -ir" },
      { es: "escribir", de: "schreiben", note: "regelmäßig -ir" },
      { es: "llegar", de: "ankommen", note: "regelmäßig -ar" }
    ]
  },
  {
    id: "verbs-action",
    title: "Die wichtigsten unregelmäßigen Verben",
    subtitle: "querer, poder, ir, hacer, gustar",
    icon: "⚡",
    tips: [
      "querer (e→ie) und poder (o→ue) ändern den Stamm – aber nur dort, wo die Betonung darauf fällt: quiero, quieres, quiere, quieren. Bei „wir/ihr“ bleibt der Stamm: queremos, queréis.",
      "Zukunft ohne neue Zeitform: „ir a + Infinitiv“. „Voy a comer“ = ich werde essen / ich gehe essen. Damit sprichst du sofort über Pläne.",
      "gustar funktioniert umgedreht: nicht „ich mag X“, sondern „mir gefällt X“. Das Verb richtet sich nach der Sache: me gusta la playa (Singular) / me gustan las tapas (Plural)."
    ],
    items: [
      { es: "querer", de: "wollen / mögen", note: "Stammwechsel e→ie" },
      { es: "quiero", de: "ich will / ich möchte", note: "querer", ex_es: "Quiero un café, por favor.", ex_de: "Ich möchte einen Kaffee, bitte." },
      { es: "quieres", de: "du willst", note: "querer" },
      { es: "quiere", de: "er/sie will, Sie wollen", note: "querer" },
      { es: "queremos", de: "wir wollen", note: "querer – kein Stammwechsel" },
      { es: "queréis", de: "ihr wollt", note: "querer – kein Stammwechsel" },
      { es: "quieren", de: "sie/Sie wollen", note: "querer" },
      { es: "me gustaría", de: "ich würde gerne", note: "höflicher als „quiero“", ex_es: "Me gustaría reservar una mesa.", ex_de: "Ich würde gerne einen Tisch reservieren." },
      { es: "poder", de: "können", note: "Stammwechsel o→ue" },
      { es: "puedo", de: "ich kann", note: "poder", ex_es: "¿Puedo pagar con tarjeta?", ex_de: "Kann ich mit Karte zahlen?" },
      { es: "puedes", de: "du kannst", note: "poder" },
      { es: "puede", de: "er/sie kann, Sie können", note: "poder", ex_es: "¿Puede ayudarme?", ex_de: "Können Sie mir helfen?" },
      { es: "podemos", de: "wir können", note: "poder – kein Stammwechsel" },
      { es: "podéis", de: "ihr könnt", note: "poder – kein Stammwechsel" },
      { es: "pueden", de: "sie/Sie können", note: "poder" },
      { es: "ir", de: "gehen / fahren", note: "völlig unregelmäßig" },
      { es: "voy", de: "ich gehe / fahre", note: "ir", ex_es: "Voy a la playa.", ex_de: "Ich gehe zum Strand." },
      { es: "vas", de: "du gehst / fährst", note: "ir" },
      { es: "va", de: "er/sie geht, Sie gehen", note: "ir", ex_es: "¿Este autobús va al centro?", ex_de: "Fährt dieser Bus ins Zentrum?" },
      { es: "vamos", de: "wir gehen", note: "ir", ex_es: "¡Vamos!", ex_de: "Los! / Auf geht's!" },
      { es: "vais", de: "ihr geht", note: "ir" },
      { es: "van", de: "sie/Sie gehen", note: "ir" },
      { es: "voy a + Infinitiv", de: "ich werde... / ich gehe...", note: "die einfache Zukunft", ex_es: "Voy a comer.", ex_de: "Ich werde essen." },
      { es: "hacer", de: "machen / tun" },
      { es: "hago", de: "ich mache", note: "hacer – unregelmäßig nur bei „ich“" },
      { es: "haces", de: "du machst", note: "hacer" },
      { es: "hace", de: "er/sie macht", note: "hacer", ex_es: "Hace calor.", ex_de: "Es ist heiß." },
      { es: "hacemos", de: "wir machen", note: "hacer" },
      { es: "hacéis", de: "ihr macht", note: "hacer" },
      { es: "hacen", de: "sie/Sie machen", note: "hacer" },
      { es: "necesito", de: "ich brauche", note: "necesitar, regelmäßig -ar", ex_es: "Necesito un médico.", ex_de: "Ich brauche einen Arzt." },
      { es: "necesitas", de: "du brauchst", note: "necesitar" },
      { es: "necesita", de: "er/sie braucht, Sie brauchen", note: "necesitar" },
      { es: "sé", de: "ich weiß", note: "saber – unregelmäßig" },
      { es: "No sé", de: "Ich weiß nicht", note: "Überlebenssatz" },
      { es: "me gusta", de: "mir gefällt / ich mag", note: "gustar + Singular", ex_es: "Me gusta esta playa.", ex_de: "Mir gefällt dieser Strand." },
      { es: "me gustan", de: "mir gefallen / ich mag", note: "gustar + Plural", ex_es: "Me gustan las tapas.", ex_de: "Ich mag Tapas." },
      { es: "no me gusta", de: "mir gefällt nicht" },
      { es: "te gusta", de: "dir gefällt", ex_es: "¿Te gusta?", ex_de: "Gefällt es dir?" },
      { es: "me encanta", de: "ich liebe es / es begeistert mich", note: "stärker als gustar", ex_es: "Me encanta España.", ex_de: "Ich liebe Spanien." }
    ]
  },
  {
    id: "restaurant",
    title: "Im Restaurant & in der Bar",
    subtitle: "Bestellen, Tapas, zahlen",
    icon: "🍽️",
    tips: [
      "Wichtig: „la carta“ ist die Speisekarte. „El menú“ (bzw. „el menú del día“) ist in Spanien das feste Tagesmenü mit mehreren Gängen zum Festpreis. Wer „el menú“ verlangt, bekommt oft das Tagesgericht statt der Karte.",
      "Der typische Bestellsatz in Spanien ist „¿Me pone...?“ (wörtlich: setzen Sie mir hin) – an der Bar Standard. Im Restaurant: „¿Me trae...?“ oder „Para mí...“.",
      "Personal ruft man nicht mit „¡Camarero!“ – das gilt als schroff. Man sagt „¡Perdone!“ oder „Por favor“ mit Blickkontakt.",
      "Trinkgeld (la propina) ist in Spanien locker: aufrunden oder ein paar Münzen liegen lassen genügt, oft gibt man auch nichts."
    ],
    items: [
      { es: "la carta", de: "die Speisekarte", note: "das willst du sehen" },
      { es: "el menú del día", de: "das Tagesmenü", note: "Festpreis, meist Vorspeise + Hauptgang + Nachtisch/Getränk" },
      { es: "¿Tienen mesa para dos?", de: "Haben Sie einen Tisch für zwei?" },
      { es: "¿Está libre esta mesa?", de: "Ist dieser Tisch frei?" },
      { es: "la terraza", de: "die Terrasse / draußen", ex_es: "¿Podemos sentarnos en la terraza?", ex_de: "Können wir draußen sitzen?" },
      { es: "Tengo una reserva a nombre de...", de: "Ich habe eine Reservierung auf den Namen..." },
      { es: "¿Qué me recomienda?", de: "Was empfehlen Sie mir?" },
      { es: "¿Me pone una caña, por favor?", de: "Ein kleines Bier, bitte?", note: "der Klassiker an der Bar" },
      { es: "¿Me trae la carta, por favor?", de: "Bringen Sie mir bitte die Karte?" },
      { es: "Quisiera...", de: "Ich hätte gerne...", note: "höfliche Form von „quiero“", ex_es: "Quisiera la paella.", ex_de: "Ich hätte gerne die Paella." },
      { es: "Para mí...", de: "Für mich...", ex_es: "Para mí, el pollo.", ex_de: "Für mich das Hähnchen." },
      { es: "De primero / De segundo", de: "Als ersten Gang / Als zweiten Gang", note: "so ist das Tagesmenü aufgebaut" },
      { es: "una ración / media ración", de: "eine Portion / eine halbe Portion", note: "so bestellt man Tapas-Gerichte" },
      { es: "para compartir", de: "zum Teilen" },
      { es: "¿Qué lleva esto?", de: "Was ist da drin?" },
      { es: "Soy vegetariano / vegetariana", de: "Ich bin Vegetarier / Vegetarierin" },
      { es: "Soy alérgico/a a...", de: "Ich bin allergisch gegen...", ex_es: "Soy alérgico a los frutos secos.", ex_de: "Ich bin allergisch gegen Nüsse." },
      { es: "sin gluten", de: "glutenfrei" },
      { es: "una botella de agua", de: "eine Flasche Wasser" },
      { es: "con gas / sin gas", de: "mit / ohne Kohlensäure" },
      { es: "¿Algo más?", de: "Sonst noch etwas?", note: "das fragt das Personal" },
      { es: "Nada más, gracias", de: "Nichts weiter, danke" },
      { es: "La cuenta, por favor", de: "Die Rechnung, bitte" },
      { es: "la propina", de: "das Trinkgeld" },
      { es: "¿Aceptan tarjeta?", de: "Nehmen Sie Karte?" },
      { es: "para llevar", de: "zum Mitnehmen" },
      { es: "para tomar aquí", de: "zum Hieressen" },
      { es: "¡Buen provecho!", de: "Guten Appetit!" },
      { es: "Está buenísimo", de: "Das ist super lecker" },
      { es: "¿Dónde están los servicios?", de: "Wo sind die Toiletten?", note: "in Lokalen sagt man „los servicios“, nicht „el baño“" }
    ]
  },
  {
    id: "food",
    title: "Essen & Trinken",
    subtitle: "Fleisch, Fisch, Tapas, Getränke",
    icon: "🥘",
    tips: [
      "Mahlzeiten in Spanien: „la comida“ ist das Mittagessen (die Hauptmahlzeit, ca. 14 Uhr), „la cena“ das Abendessen – oft erst ab 21 Uhr.",
      "Auf der Karte verrät die Zubereitung viel: a la plancha (kurz gebraten), frito (frittiert), al horno (im Ofen), a la parrilla (vom Grill).",
      "„Agua“ ist weiblich, bekommt im Singular aber „el“: el agua fría. Im Plural wieder „las aguas“."
    ],
    items: [
      { es: "el desayuno", de: "das Frühstück" },
      { es: "la comida", de: "das Mittagessen", note: "in Spanien die Hauptmahlzeit" },
      { es: "la cena", de: "das Abendessen", note: "oft erst ab 21 Uhr" },
      { es: "la carne", de: "das Fleisch" },
      { es: "el pollo", de: "das Hähnchen" },
      { es: "el cerdo", de: "das Schweinefleisch" },
      { es: "la ternera", de: "das Rind-/Kalbfleisch", note: "so steht Rindfleisch meist auf spanischen Karten" },
      { es: "el cordero", de: "das Lammfleisch" },
      { es: "el jamón", de: "der Schinken", note: "jamón serrano = luftgetrockneter Schinken" },
      { es: "el pescado", de: "der Fisch" },
      { es: "el marisco", de: "die Meeresfrüchte" },
      { es: "las gambas", de: "die Garnelen" },
      { es: "los calamares", de: "der Tintenfisch", note: "meist als frittierte Ringe serviert" },
      { es: "el pan", de: "das Brot" },
      { es: "el bocadillo", de: "das belegte Brötchen", note: "das spanische Standard-Snack" },
      { es: "el queso", de: "der Käse" },
      { es: "el huevo", de: "das Ei" },
      { es: "la ensalada", de: "der Salat" },
      { es: "la sopa", de: "die Suppe" },
      { es: "el arroz", de: "der Reis" },
      { es: "las patatas", de: "die Kartoffeln", note: "in Spanien „patatas“, in Lateinamerika „papas“" },
      { es: "las patatas fritas", de: "die Pommes / Chips" },
      { es: "las verduras", de: "das Gemüse" },
      { es: "la fruta", de: "das Obst" },
      { es: "el postre", de: "die Nachspeise" },
      { es: "el helado", de: "das Eis" },
      { es: "el agua", de: "das Wasser", note: "weiblich, aber „el agua“: el agua fría" },
      { es: "el agua del grifo", de: "das Leitungswasser" },
      { es: "el hielo", de: "das Eis (Würfel)", ex_es: "sin hielo, por favor", ex_de: "ohne Eis, bitte" },
      { es: "el vino tinto", de: "der Rotwein", note: "Rotwein ist „tinto“, nie „rojo“" },
      { es: "el vino blanco", de: "der Weißwein" },
      { es: "la cerveza", de: "das Bier" },
      { es: "una caña", de: "ein kleines Bier vom Fass", note: "die spanische Standardbestellung" },
      { es: "el café con leche", de: "der Milchkaffee" },
      { es: "el café solo", de: "der Espresso" },
      { es: "el té", de: "der Tee" },
      { es: "el zumo", de: "der Saft", note: "in Spanien „zumo“, in Lateinamerika „jugo“" },
      { es: "las tapas", de: "kleine Häppchen zum Getränk" },
      { es: "la paella", de: "die Paella (Reisgericht)" },
      { es: "la tortilla de patatas", de: "das spanische Kartoffel-Omelett", note: "in Spanien ist „tortilla“ ein Omelett, kein Fladenbrot" },
      { es: "el aceite de oliva", de: "das Olivenöl" },
      { es: "la sal / la pimienta", de: "das Salz / der Pfeffer" },
      { es: "el azúcar", de: "der Zucker" },
      { es: "a la plancha", de: "kurz gebraten", note: "typisch für Fisch" },
      { es: "frito / frita", de: "frittiert" },
      { es: "al horno", de: "im Ofen gebacken" },
      { es: "picante", de: "scharf" },
      { es: "dulce", de: "süß" },
      { es: "salado / salada", de: "salzig" }
    ]
  },
  {
    id: "colors",
    title: "Farben",
    subtitle: "rojo, azul, verde",
    icon: "🎨",
    tips: [
      "Farben richten sich nach dem Nomen: el coche rojo, la casa roja, los coches rojos.",
      "Farben auf -e oder Konsonant (verde, azul, gris, marrón) haben keine eigene weibliche Form – nur Plural: azules, grises, marrones.",
      "„naranja“ und „rosa“ sind eigentlich Nomen (Orange, Rose) und bleiben unverändert: una camiseta naranja."
    ],
    items: [
      { es: "rojo / roja", de: "rot" },
      { es: "azul", de: "blau", note: "keine weibliche Form" },
      { es: "verde", de: "grün", note: "keine weibliche Form" },
      { es: "amarillo / amarilla", de: "gelb" },
      { es: "naranja", de: "orange", note: "unveränderlich" },
      { es: "morado / morada", de: "lila / violett" },
      { es: "rosa", de: "rosa", note: "unveränderlich" },
      { es: "blanco / blanca", de: "weiß" },
      { es: "negro / negra", de: "schwarz" },
      { es: "gris", de: "grau", note: "keine weibliche Form" },
      { es: "marrón", de: "braun", note: "Plural: marrones" },
      { es: "dorado / dorada", de: "golden" },
      { es: "plateado / plateada", de: "silbern" },
      { es: "claro", de: "hell", ex_es: "azul claro", ex_de: "hellblau" },
      { es: "oscuro", de: "dunkel", ex_es: "verde oscuro", ex_de: "dunkelgrün" }
    ]
  },
  {
    id: "shopping",
    title: "Einkaufen",
    subtitle: "Markt, Kleidung, Preise",
    icon: "🛍️",
    tips: [
      "Bei Kleidung fragt man nach „la talla“ (Größe), bei Schuhen nach „el número“.",
      "Viele kleine Läden machen mittags Siesta (ca. 14–17 Uhr) und sonntags ganz zu."
    ],
    items: [
      { es: "la tienda", de: "der Laden" },
      { es: "el mercado", de: "der Markt" },
      { es: "el supermercado", de: "der Supermarkt" },
      { es: "¿Cuánto cuesta esto?", de: "Wie viel kostet das?" },
      { es: "¿Cuánto es en total?", de: "Wie viel macht das insgesamt?" },
      { es: "Es muy caro", de: "Das ist sehr teuer" },
      { es: "Es barato", de: "Das ist günstig" },
      { es: "¿Tienen esto en la talla...?", de: "Haben Sie das in Größe...?", note: "talla = Kleidergröße" },
      { es: "¿Qué número usa?", de: "Welche Schuhgröße haben Sie?" },
      { es: "más grande / más pequeño", de: "größer / kleiner" },
      { es: "el probador", de: "die Umkleidekabine" },
      { es: "¿Me lo puedo probar?", de: "Kann ich es anprobieren?" },
      { es: "en efectivo", de: "bar" },
      { es: "con tarjeta", de: "mit Karte" },
      { es: "el cambio", de: "das Wechselgeld" },
      { es: "las rebajas", de: "der Ausverkauf / Sale" },
      { es: "abierto / cerrado", de: "geöffnet / geschlossen" },
      { es: "el ticket / el recibo", de: "der Kassenbon" },
      { es: "una bolsa", de: "eine Tüte" },
      { es: "Solo estoy mirando, gracias", de: "Ich schaue nur, danke" },
      { es: "Me lo llevo", de: "Ich nehme es" },
      { es: "¿Puede envolverlo?", de: "Können Sie es einpacken?" }
    ]
  },
  {
    id: "directions",
    title: "Wegbeschreibung & Unterwegs",
    subtitle: "links, rechts, Bus, Bahnhof",
    icon: "🧭",
    tips: [
      "In Spanien heißt „den Bus nehmen“ ganz normal „coger el autobús“. In Lateinamerika solltest du dieses Verb meiden – dort ist es vulgär. Neutral geht immer „tomar“.",
      "Wenn du eine Wegbeschreibung nicht verstehst: „Más despacio, por favor“ oder „¿Me lo puede señalar en el mapa?“"
    ],
    items: [
      { es: "¿Dónde está...?", de: "Wo ist...?", ex_es: "¿Dónde está la estación?", ex_de: "Wo ist der Bahnhof?" },
      { es: "¿Cómo llego a...?", de: "Wie komme ich zu...?" },
      { es: "¿Está lejos?", de: "Ist es weit?" },
      { es: "Está cerca", de: "Es ist in der Nähe" },
      { es: "a la derecha", de: "rechts" },
      { es: "a la izquierda", de: "links" },
      { es: "todo recto", de: "geradeaus" },
      { es: "la primera calle a la derecha", de: "die erste Straße rechts" },
      { es: "la esquina", de: "die Ecke" },
      { es: "al lado de", de: "neben" },
      { es: "enfrente de", de: "gegenüber von" },
      { es: "detrás de", de: "hinter" },
      { es: "delante de", de: "vor" },
      { es: "entre", de: "zwischen" },
      { es: "la calle", de: "die Straße" },
      { es: "la plaza", de: "der Platz" },
      { es: "la playa", de: "der Strand" },
      { es: "el centro", de: "die Innenstadt" },
      { es: "a pie", de: "zu Fuß" },
      { es: "coger el autobús", de: "den Bus nehmen", note: "so sagt man es in Spanien" },
      { es: "la parada de autobús", de: "die Bushaltestelle" },
      { es: "el metro", de: "die U-Bahn" },
      { es: "la estación de tren", de: "der Bahnhof" },
      { es: "el aeropuerto", de: "der Flughafen" },
      { es: "un billete", de: "eine Fahrkarte", note: "in Spanien „billete“, in Lateinamerika „boleto“" },
      { es: "ida y vuelta", de: "hin und zurück" },
      { es: "solo ida", de: "nur Hinfahrt" },
      { es: "¿Este autobús va al centro?", de: "Fährt dieser Bus ins Zentrum?" },
      { es: "el taxi", de: "das Taxi" },
      { es: "el alquiler de coches", de: "die Autovermietung" },
      { es: "¿Me lo puede señalar en el mapa?", de: "Können Sie mir das auf der Karte zeigen?" }
    ]
  },
  {
    id: "emergency",
    title: "Notfälle & Gesundheit",
    subtitle: "Arzt, Apotheke, Polizei",
    icon: "🚨",
    tips: [
      "Die Notrufnummer in ganz Spanien (und der EU) ist 112 – Polizei, Feuerwehr und Rettung zugleich, auch auf Englisch erreichbar.",
      "Apotheken (farmacia) mit grünem Kreuz beraten in Spanien viel weiter als in Deutschland – für kleine Beschwerden ist das die erste Adresse.",
      "„Me duele...“ heißt wörtlich „mir schmerzt...“ – danach kommt der Körperteil mit Artikel: me duele la cabeza."
    ],
    items: [
      { es: "¡Socorro!", de: "Hilfe!", note: "der klassische Notruf" },
      { es: "¡Ayuda!", de: "Hilfe!" },
      { es: "Llame al 112", de: "Rufen Sie die 112", note: "Notruf in ganz Spanien" },
      { es: "Necesito ayuda", de: "Ich brauche Hilfe" },
      { es: "Necesito un médico", de: "Ich brauche einen Arzt" },
      { es: "Llame a un médico, por favor", de: "Rufen Sie bitte einen Arzt" },
      { es: "la farmacia", de: "die Apotheke" },
      { es: "¿Hay una farmacia cerca?", de: "Gibt es hier eine Apotheke in der Nähe?" },
      { es: "el hospital", de: "das Krankenhaus" },
      { es: "urgencias", de: "die Notaufnahme" },
      { es: "una ambulancia", de: "ein Krankenwagen" },
      { es: "la policía", de: "die Polizei" },
      { es: "Me duele aquí", de: "Hier tut es weh" },
      { es: "Me duele la cabeza", de: "Ich habe Kopfschmerzen" },
      { es: "Me duele el estómago", de: "Ich habe Bauchschmerzen" },
      { es: "No me encuentro bien", de: "Ich fühle mich nicht gut" },
      { es: "Estoy mareado / mareada", de: "Mir ist schwindelig" },
      { es: "Tengo fiebre", de: "Ich habe Fieber" },
      { es: "una alergia", de: "eine Allergie" },
      { es: "la receta", de: "das Rezept" },
      { es: "Me he quemado con el sol", de: "Ich habe einen Sonnenbrand" },
      { es: "el protector solar", de: "die Sonnencreme" },
      { es: "He perdido mi pasaporte", de: "Ich habe meinen Pass verloren" },
      { es: "Me han robado", de: "Ich wurde bestohlen" },
      { es: "el seguro de viaje", de: "die Reiseversicherung" },
      { es: "la embajada", de: "die Botschaft" }
    ]
  },
  {
    id: "smalltalk",
    title: "Small Talk & Alltag",
    subtitle: "Sich vorstellen, Gespräche retten",
    icon: "💬",
    tips: [
      "Die zwei nützlichsten Sätze überhaupt: „¿Cómo se dice ... en español?“ (Wie sagt man ...?) und „No entiendo“ (Ich verstehe nicht). Damit kommst du aus jeder Situation heraus.",
      "Spanier freuen sich sehr, wenn man es auf Spanisch versucht – „Estoy aprendiendo español“ öffnet Türen."
    ],
    items: [
      { es: "¿Cómo te llamas?", de: "Wie heißt du?" },
      { es: "Me llamo...", de: "Ich heiße..." },
      { es: "¿De dónde eres?", de: "Woher kommst du?" },
      { es: "Soy de Alemania", de: "Ich komme aus Deutschland" },
      { es: "Somos de Alemania", de: "Wir kommen aus Deutschland" },
      { es: "¿Cuántos años tienes?", de: "Wie alt bist du?" },
      { es: "Tengo... años", de: "Ich bin... Jahre alt" },
      { es: "Estoy de vacaciones", de: "Ich bin im Urlaub" },
      { es: "Estamos de vacaciones", de: "Wir sind im Urlaub" },
      { es: "Estoy casado / casada", de: "Ich bin verheiratet" },
      { es: "mi mujer / mi marido", de: "meine Frau / mein Mann" },
      { es: "¿Es tu primera vez en España?", de: "Bist du das erste Mal in Spanien?" },
      { es: "¿Hablas inglés?", de: "Sprichst du Englisch?" },
      { es: "Hablo un poco de español", de: "Ich spreche ein bisschen Spanisch" },
      { es: "Estoy aprendiendo español", de: "Ich lerne Spanisch" },
      { es: "No entiendo", de: "Ich verstehe nicht" },
      { es: "¿Puede repetir, por favor?", de: "Können Sie das bitte wiederholen?" },
      { es: "Más despacio, por favor", de: "Langsamer, bitte" },
      { es: "¿Cómo se dice... en español?", de: "Wie sagt man... auf Spanisch?" },
      { es: "¿Qué significa esto?", de: "Was bedeutet das?" },
      { es: "¡Qué bien!", de: "Wie schön! / Klasse!" },
      { es: "¡Qué bonito!", de: "Wie hübsch!" },
      { es: "¡Qué calor!", de: "Was für eine Hitze!" },
      { es: "un placer", de: "eine Freude", ex_es: "Ha sido un placer.", ex_de: "Es war eine Freude." }
    ]
  }
];
